services:
  # Seu Dashboard e Motor de Email Integrados (Tudo Próprio em Node.js)
  zimamail-app:
    image: werikoliveira/email:latest
    container_name: zimamail-app
    restart: always
    ports:
      - "3000:3000" # Dashboard
      - "25:2525"   # SMTP (Entrada) -> Mapeia para o motor Node interno
      - "587:587"   # SMTP Submission
      - "465:465"   # SMTPS
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      - /DATA/AppData/zimamail/app/data:/app/data
