-- SUPABASE MIGRATION SCRIPT
-- Copy and paste this into your Supabase SQL Editor

-- 1. Table: accounts
CREATE TABLE IF NOT EXISTS accounts (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT,
  role TEXT DEFAULT 'user',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table: campaigns
CREATE TABLE IF NOT EXISTS campaigns (
  id TEXT PRIMARY KEY,
  name TEXT,
  subject TEXT,
  body TEXT,
  "from" TEXT,
  delay INTEGER DEFAULT 500,
  scheduled_at TIMESTAMPTZ,
  status TEXT DEFAULT 'pending',
  stats JSONB DEFAULT '{"total": 0, "sent": 0, "failed": 0, "opens": 0, "clicks": 0}'::jsonb,
  recipients JSONB DEFAULT '[]'::jsonb,
  events JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table: domains
CREATE TABLE IF NOT EXISTS domains (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Table: drafts
CREATE TABLE IF NOT EXISTS drafts (
  id TEXT PRIMARY KEY,
  subject TEXT,
  body TEXT,
  "from" TEXT,
  "to" TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Table: email_lists
CREATE TABLE IF NOT EXISTS email_lists (
  id TEXT PRIMARY KEY,
  name TEXT,
  recipients JSONB DEFAULT '[]'::jsonb,
  count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Table: emails (Inbox)
CREATE TABLE IF NOT EXISTS emails (
  id TEXT PRIMARY KEY,
  from_addr TEXT,
  to_addr TEXT,
  subject TEXT,
  body TEXT,
  received_at TIMESTAMPTZ DEFAULT NOW(),
  read BOOLEAN DEFAULT FALSE
);

-- 7. Table: logs
CREATE TABLE IF NOT EXISTS logs (
  id TEXT PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  message TEXT,
  type TEXT DEFAULT 'info',
  metadata JSONB DEFAULT '{}'::jsonb
);

-- 8. Table: relays
CREATE TABLE IF NOT EXISTS relays (
  id TEXT PRIMARY KEY,
  name TEXT,
  host TEXT,
  port TEXT,
  "user" TEXT,
  pass TEXT,
  quota INTEGER DEFAULT 1000,
  sent INTEGER DEFAULT 0,
  api_key TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Table: sent
CREATE TABLE IF NOT EXISTS sent (
  id TEXT PRIMARY KEY,
  "to" TEXT,
  subject TEXT,
  body TEXT,
  "from" TEXT,
  sent_at TIMESTAMPTZ DEFAULT NOW(),
  relay TEXT
);

-- 10. Table: settings
CREATE TABLE IF NOT EXISTS settings (
  id TEXT PRIMARY KEY DEFAULT 'main',
  smtp_host TEXT,
  smtp_port INTEGER DEFAULT 587,
  smtp_user TEXT,
  smtp_pass TEXT,
  domain TEXT,
  delivery_mode TEXT DEFAULT 'internal',
  cf_token TEXT,
  cf_zone TEXT
);

-- 11. Table: trash
CREATE TABLE IF NOT EXISTS trash (
  id TEXT PRIMARY KEY,
  content JSONB,
  deleted_at TIMESTAMPTZ DEFAULT NOW()
);

-- Initial accounts (Based on hardcoded values or previous data)
INSERT INTO accounts (id, email, password, name, role) VALUES ('1', 'werikplaystore@gmail.com', 'We12wi25k#3912*', 'Werik', 'admin') ON CONFLICT DO NOTHING;

-- Initial settings
INSERT INTO settings (id, domain) VALUES ('main', 'amplifamarketing.com.br') ON CONFLICT DO NOTHING;
